/**
 * SLEEPEE ENTERPRISE INDUSTRIAL ENGINEERING KNOWLEDGE BASE
 * =========================================================
 * 100% Internal, Offline, Rule-Based Industrial Mattress Manufacturing Knowledge Matrix.
 * Zero external AI runtime dependencies. Operating Cost: $0/month.
 */

export interface MaterialSpec {
  id: string;
  nameAr: string;
  nameEn: string;
  category: 'spring' | 'foam' | 'felt' | 'fiber' | 'fabric';
  code: string;
  standardThicknessMinCm: number;
  standardThicknessMaxCm: number;
  standardThicknessDefaultCm: number;
  densityRangeKgM3: [number, number]; // [min, max], 0 for springs/felts
  defaultDensityKgM3: number;
  costPerM2Sar: number; // Base cost SAR / m²
  supplierName: string;
  supplierCode: string;
  firmnessFactor: number; // 1 (Ultra soft) to 10 (Extra firm)
  durabilityYears: number;
  thermalConductivity: 'high' | 'medium' | 'neutral' | 'insulating';
  sasoCompliant: boolean;
  medicalGrade: boolean;
  hotelGrade: boolean;
  notesAr: string;
  notesEn: string;
}

export interface MattressStandardMatrix {
  marketSegment: 'Hotel' | 'Medical' | 'Retail' | 'Residential' | 'Export';
  budgetLevel: 'Economy' | 'Standard' | 'Premium' | 'Luxury';
  recommendedSpring: string;
  recommendedCoreFoam: string;
  recommendedTopper: string;
  recommendedFabric: string;
  minTargetHeightCm: number;
  maxTargetHeightCm: number;
  defaultHeightCm: number;
  minFoamDensity: number;
  standardWarrantyYears: number;
  defaultWarrantyType: '10 Years' | '7 Years' | '5 Years' | 'Hybrid' | 'Declining' | 'Custom';
  riskProfile: 'Low' | 'Medium' | 'High';
  engineeringJustificationAr: string;
  engineeringJustificationEn: string;
}

export const SLEEPEE_SPRING_SYSTEMS: Record<string, MaterialSpec> = {
  'Pocket Spring': {
    id: 'mat-spring-pocket',
    nameAr: 'سوست جيبية منفصلة (Pocket Spring)',
    nameEn: 'Independent Pocket Springs (2.0mm/1.8mm Wire)',
    category: 'spring',
    code: 'SP-PCK-200',
    standardThicknessMinCm: 12,
    standardThicknessMaxCm: 22,
    standardThicknessDefaultCm: 16,
    densityRangeKgM3: [0, 0],
    defaultDensityKgM3: 0,
    costPerM2Sar: 110,
    supplierName: 'مصنع سليب إي للهندسة المعدنية (Sleepee Springs Division)',
    supplierCode: 'SUP-SLP-SP01',
    firmnessFactor: 6.5,
    durabilityYears: 10,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'شاسيه سوست جيبية منفصلة ملفوفة بأقمشة غير منسوجة لعزل الحركة التام وتوفير دعم هيدروديناميكي دقيق لفقرات العمود الفقري.',
    notesEn: 'Individually encased pocket springs offering zero-motion transfer and contouring ergonomic spinal support.'
  },
  'Micro Pocket': {
    id: 'mat-spring-micro',
    nameAr: 'سوست مايكرو بوكيت عالية الكثافة (Micro Pocket)',
    nameEn: 'High-Density Micro Pocket Springs (1.3mm Wire - 650/m²)',
    category: 'spring',
    code: 'SP-MIC-650',
    standardThicknessMinCm: 6,
    standardThicknessMaxCm: 15,
    standardThicknessDefaultCm: 10,
    densityRangeKgM3: [0, 0],
    defaultDensityKgM3: 0,
    costPerM2Sar: 145,
    supplierName: 'الشريك الألماني للسوست الطبية (German Precision Springs)',
    supplierCode: 'SUP-GER-SP02',
    firmnessFactor: 7.5,
    durabilityYears: 12,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'سوست دقيقة بأعداد مضاعفة (أكثر من 650 سستة/م²) للاستخدام الطبي الفاخر وتخفيف نقاط الضغط بنسبة 40%.',
    notesEn: 'Ultra-dense micro springs designed for medical ergonomic pressure relief and luxury contouring.'
  },
  'Dual Pocket': {
    id: 'mat-spring-dual',
    nameAr: 'نظام سوست مزدوج الطبقات (Dual Pocket System)',
    nameEn: 'Dual Pocket Two-Tier Spring System',
    category: 'spring',
    code: 'SP-DUAL-800',
    standardThicknessMinCm: 16,
    standardThicknessMaxCm: 24,
    standardThicknessDefaultCm: 20,
    densityRangeKgM3: [0, 0],
    defaultDensityKgM3: 0,
    costPerM2Sar: 165,
    supplierName: 'مصنع سليب إي للهندسة المعدنية (Sleepee Springs Division)',
    supplierCode: 'SUP-SLP-SP03',
    firmnessFactor: 8.0,
    durabilityYears: 15,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: false,
    hotelGrade: true,
    notesAr: 'شاسيه هجين بطبقتين من السوست الجيبية للوزن الثقيل والفنادق الرئاسية الراقية 7 نجوم.',
    notesEn: 'Double-decker pocket coil engineering for ultra-luxury hospitality and heavy-duty load distribution.'
  },
  'Bonnell Spring': {
    id: 'mat-spring-bonnell',
    nameAr: 'سوست بونيل حلزونية متصلة (Bonnell Spring)',
    nameEn: 'Connected Bonnell Spring Core (2.2mm Carbon Steel)',
    category: 'spring',
    code: 'SP-BON-220',
    standardThicknessMinCm: 12,
    standardThicknessMaxCm: 18,
    standardThicknessDefaultCm: 15,
    densityRangeKgM3: [0, 0],
    defaultDensityKgM3: 0,
    costPerM2Sar: 65,
    supplierName: 'المورد الوطني لشاسيهات السوست (National Steel Spring Co.)',
    supplierCode: 'SUP-NAT-SP04',
    firmnessFactor: 7.0,
    durabilityYears: 7,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: false,
    hotelGrade: false,
    notesAr: 'شاسيه سوست كربوني كلاسيكي متصل عالي الصلابة، مزود بحلقات فولاذية ومقاوم للهبوط الميكانيكي الاقتصادي.',
    notesEn: 'Traditional continuous carbon steel wire frame with robust edge support border wires for economical durability.'
  },
  'No Springs': {
    id: 'mat-spring-none',
    nameAr: 'بدون شاسيه سوست (قلب إسفنجي كامل Full Foam Core)',
    nameEn: 'Solid Foam / Latex Core (All-Foam Construction)',
    category: 'spring',
    code: 'SP-NONE-000',
    standardThicknessMinCm: 0,
    standardThicknessMaxCm: 0,
    standardThicknessDefaultCm: 0,
    densityRangeKgM3: [0, 0],
    defaultDensityKgM3: 0,
    costPerM2Sar: 0,
    supplierName: 'خط تصنيع الإسفنج الداخلي (Internal Production)',
    supplierCode: 'INT-CORE-00',
    firmnessFactor: 5.0,
    durabilityYears: 10,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'هيكل إسفنجي أو لاتكس متكامل بدون أجزاء معدنية، مثالي للمراتب الطبية وقواعد الأسرة القابلة للتعديل.',
    notesEn: 'Pure monolithic or multi-layered orthopedic foam core without metallic spring components.'
  }
};

export const SLEEPEE_FOAM_TYPES: Record<string, MaterialSpec> = {
  'HR Foam': {
    id: 'mat-foam-hr',
    nameAr: 'إسفنج عالي المرونة والارتداد (HR Foam)',
    nameEn: 'High Resilience Foam (HR Foam D35-D45)',
    category: 'foam',
    code: 'FM-HR-035',
    standardThicknessMinCm: 2,
    standardThicknessMaxCm: 15,
    standardThicknessDefaultCm: 4,
    densityRangeKgM3: [30, 45],
    defaultDensityKgM3: 35,
    costPerM2Sar: 35,
    supplierName: 'مصنع رغوة سليب إي المتطورة (Sleepee Advanced Polymers)',
    supplierCode: 'SUP-SLP-FM01',
    firmnessFactor: 6.0,
    durabilityYears: 10,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'إسفنج عالي الارتداد بخلايا مفتوحة يضمن استعادة فورية للشكل، وتبريد طبيعي ومقاومة فائقة للتقادم.',
    notesEn: 'Open-cell high-resilience foam providing instant recovery, pressure distribution and long-term elasticity.'
  },
  'Memory Foam': {
    id: 'mat-foam-mem',
    nameAr: 'إسفنج الذاكرة الميموري فوم الذكي (Memory Foam)',
    nameEn: 'Viscoelastic Memory Foam (D50-D65)',
    category: 'foam',
    code: 'FM-MEM-050',
    standardThicknessMinCm: 2,
    standardThicknessMaxCm: 8,
    standardThicknessDefaultCm: 4,
    densityRangeKgM3: [45, 65],
    defaultDensityKgM3: 50,
    costPerM2Sar: 55,
    supplierName: 'مصنع رغوة سليب إي المتطورة (Sleepee Advanced Polymers)',
    supplierCode: 'SUP-SLP-FM02',
    firmnessFactor: 4.0,
    durabilityYears: 8,
    thermalConductivity: 'insulating',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'رغوة مرنة لزجة تتشكل مع حرارة الجسم لاحتواء المنحنيات وإلغاء نقاط الضغط تماماً عن المفاصل.',
    notesEn: 'Temperature-responsive viscoelastic polymer molding perfectly around anatomical contours.'
  },
  'Gel Memory Foam': {
    id: 'mat-foam-gel',
    nameAr: 'إسفنج الذاكرة المبرد بحبيبات الجل (Gel Memory Foam)',
    nameEn: 'Thermo-Regulating Gel Infused Memory Foam (D55)',
    category: 'foam',
    code: 'FM-GEL-055',
    standardThicknessMinCm: 2,
    standardThicknessMaxCm: 6,
    standardThicknessDefaultCm: 3,
    densityRangeKgM3: [50, 65],
    defaultDensityKgM3: 55,
    costPerM2Sar: 70,
    supplierName: 'مصنع رغوة سليب إي المتطورة (Sleepee Advanced Polymers)',
    supplierCode: 'SUP-SLP-FM03',
    firmnessFactor: 4.5,
    durabilityYears: 9,
    thermalConductivity: 'high',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'ميموري فوم مدمج بحبيبات التبريد الماصة للحرارة لتعديل المناخ الحراري أثناء النوم وتخفيض حرارة السطح بـ 2 درجة مئوية.',
    notesEn: 'Phase-change cooling gel micro-capsules infused into memory foam for active temperature moderation.'
  },
  'Latex': {
    id: 'mat-foam-latex',
    nameAr: 'لاتكس طبيعي مرن معقم (Natural Latex)',
    nameEn: '100% Natural Dunlop/Talalay Latex (D75-D85)',
    category: 'foam',
    code: 'FM-LTX-075',
    standardThicknessMinCm: 2,
    standardThicknessMaxCm: 10,
    standardThicknessDefaultCm: 4,
    densityRangeKgM3: [65, 85],
    defaultDensityKgM3: 75,
    costPerM2Sar: 90,
    supplierName: 'المستورد الماليزي للاتكس الطبيعي (Malaysian Natural Latex)',
    supplierCode: 'SUP-MAL-LT01',
    firmnessFactor: 5.5,
    durabilityYears: 15,
    thermalConductivity: 'high',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'لاتكس عضوي مستخلص من أشجار المطاط، مضاد طبيعي لعث الفراش والبكتيريا، مع تهوية فائقة ومرونة مستمرة لعقود.',
    notesEn: 'Eco-harvested natural latex rubber with pin-core ventilation, hypoallergenic and inherently anti-microbial.'
  },
  'Rebonded Foam': {
    id: 'mat-foam-reb',
    nameAr: 'إسفنج ريبوند طبي مضغوط فائق الصلابة (Rebonded Foam)',
    nameEn: 'High-Density Medical Rebonded Foam (D70-D110)',
    category: 'foam',
    code: 'FM-REB-080',
    standardThicknessMinCm: 2,
    standardThicknessMaxCm: 15,
    standardThicknessDefaultCm: 5,
    densityRangeKgM3: [70, 110],
    defaultDensityKgM3: 80,
    costPerM2Sar: 28,
    supplierName: 'مصنع رغوة سليب إي المتطورة (Sleepee Advanced Polymers)',
    supplierCode: 'SUP-SLP-FM04',
    firmnessFactor: 9.0,
    durabilityYears: 12,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: false,
    notesAr: 'إسفنج طبي مضغوط بكثافة عالية جداً لتقويم وتثبيت العمود الفقري ومنع الانحناء للأوزان الثقيلة والاحتياجات الطبية.',
    notesEn: 'Ultra-dense compressed bonded foam engineered for orthopedic rigidity, zero sagging, and heavy medical loads.'
  },
  'Hard Foam': {
    id: 'mat-foam-hard',
    nameAr: 'إسفنج دعم صلب للقاعدة (Hard Foam Base)',
    nameEn: 'High-Density Support Hard Foam (D30-D36)',
    category: 'foam',
    code: 'FM-HRD-032',
    standardThicknessMinCm: 1.5,
    standardThicknessMaxCm: 8,
    standardThicknessDefaultCm: 3,
    densityRangeKgM3: [28, 36],
    defaultDensityKgM3: 32,
    costPerM2Sar: 22,
    supplierName: 'مصنع رغوة سليب إي المتطورة (Sleepee Advanced Polymers)',
    supplierCode: 'SUP-SLP-FM05',
    firmnessFactor: 8.0,
    durabilityYears: 8,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'طبقة أساس داعمة متينة توضع أسفل السوست أو في قاع المرتبة لضمان استقرار الهيكل الميكانيكي.',
    notesEn: 'Structural foundation barrier foam ensuring stable base platform support across bed slats.'
  },
  'Soft Foam': {
    id: 'mat-foam-soft',
    nameAr: 'إسفنج تطرية فائق النعومة (Super Soft Foam)',
    nameEn: 'Comfort Plush Soft Foam (D20-D25)',
    category: 'foam',
    code: 'FM-SFT-022',
    standardThicknessMinCm: 1,
    standardThicknessMaxCm: 5,
    standardThicknessDefaultCm: 2,
    densityRangeKgM3: [20, 26],
    defaultDensityKgM3: 24,
    costPerM2Sar: 18,
    supplierName: 'مصنع رغوة سليب إي المتطورة (Sleepee Advanced Polymers)',
    supplierCode: 'SUP-SLP-FM06',
    firmnessFactor: 3.0,
    durabilityYears: 6,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: false,
    hotelGrade: true,
    notesAr: 'إسفنج تطرية ناعم يدمج في طبقات الكبتونية لملامسة ناعمة وشعور فندقي فخم بالاحتضان.',
    notesEn: 'Plush cloud-like cushioning foam for outer upholstery comfort and body cradling sensation.'
  }
};

export const SLEEPEE_FELT_AND_FIBER_TYPES: Record<string, MaterialSpec> = {
  'Cotton Felt': {
    id: 'mat-felt-cotton',
    nameAr: 'لباد قطني عازل معالج حرارياً (Cotton Felt)',
    nameEn: 'Thermobonded Cotton Insulator Felt (900g/m²)',
    category: 'felt',
    code: 'FL-COT-900',
    standardThicknessMinCm: 0.5,
    standardThicknessMaxCm: 1.5,
    standardThicknessDefaultCm: 1.0,
    densityRangeKgM3: [800, 1000],
    defaultDensityKgM3: 900,
    costPerM2Sar: 12,
    supplierName: 'شركة النسيج العازل الصناعي (Industrial Textile Felt Co.)',
    supplierCode: 'SUP-IND-FL01',
    firmnessFactor: 7.5,
    durabilityYears: 10,
    thermalConductivity: 'insulating',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'طبقة لباد معالج حرارياً تفصل بين شاسيه السوست وطبقات الإسفنج لحمايتها من الاختراق وتوزيع الحمل بالتساوي.',
    notesEn: 'Heavyweight thermal-bonded needle-punched felt insulator pad shielding comfort layers from springs.'
  },
  'Polyester Felt': {
    id: 'mat-felt-poly',
    nameAr: 'لباد بوليستر إبرة صناعي (Polyester Felt)',
    nameEn: 'Needle-Punched Polyester Felt (600g/m²)',
    category: 'felt',
    code: 'FL-POL-600',
    standardThicknessMinCm: 0.4,
    standardThicknessMaxCm: 1.0,
    standardThicknessDefaultCm: 0.8,
    densityRangeKgM3: [500, 700],
    defaultDensityKgM3: 600,
    costPerM2Sar: 8,
    supplierName: 'شركة النسيج العازل الصناعي (Industrial Textile Felt Co.)',
    supplierCode: 'SUP-IND-FL02',
    firmnessFactor: 6.5,
    durabilityYears: 7,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: false,
    hotelGrade: false,
    notesAr: 'طبقة عازلة اقتصادية من ألياف البوليستر الإبرية لعزل السوست في المنتجات الاقتصادية والمعيارية.',
    notesEn: 'Durable synthetic barrier felt for standard product isolation and puncture protection.'
  },
  'Fiber': {
    id: 'mat-fiber-silicon',
    nameAr: 'ألياف مايكروفايبر سيليكونية حرارية (Siliconized Fiber)',
    nameEn: 'Hollow Siliconized Virgin Microfiber (300g/m²)',
    category: 'fiber',
    code: 'FB-SIL-300',
    standardThicknessMinCm: 0.5,
    standardThicknessMaxCm: 2.0,
    standardThicknessDefaultCm: 1.0,
    densityRangeKgM3: [250, 400],
    defaultDensityKgM3: 300,
    costPerM2Sar: 10,
    supplierName: 'مصنع الألياف الصناعية المتقدمة (Advanced Fiber Works)',
    supplierCode: 'SUP-ADV-FB01',
    firmnessFactor: 2.0,
    durabilityYears: 8,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'ألياف هولو فايبر سيليكونية منفوخة لمنح الكبتوني العلوي نعومة وانتفاخاً فندقياً ناعماً مع الحفاظ على التنفس.',
    notesEn: 'Siliconized polyester staple fiber providing loft, breathability, and resilient plush surface texture.'
  }
};

export const SLEEPEE_FABRIC_TYPES: Record<string, MaterialSpec> = {
  'Knitted Fabric': {
    id: 'mat-fab-knit',
    nameAr: 'قماش منسوج ناعم عالي الكثافة (Knitted Fabric)',
    nameEn: 'Premium Heavyweight Knitted Jacquard (350g/m²)',
    category: 'fabric',
    code: 'TX-KNT-350',
    standardThicknessMinCm: 0.5,
    standardThicknessMaxCm: 2.0,
    standardThicknessDefaultCm: 1.0,
    densityRangeKgM3: [300, 400],
    defaultDensityKgM3: 350,
    costPerM2Sar: 24,
    supplierName: 'مجمع نسيج سليبي المعتمد (Sleepee Master Textile)',
    supplierCode: 'SUP-TEX-KN01',
    firmnessFactor: 4.0,
    durabilityYears: 10,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'قماش تريكو فاخر محاك بمرونة تمدد بأربعة اتجاهات ليتماشى مع انحناءات الجسم دون شد أو إجهاد.',
    notesEn: '4-way stretch circular knit fabric with soft touch and breathable micro-ventilation.'
  },
  'Cooling Fabric': {
    id: 'mat-fab-cool',
    nameAr: 'قماش التبريد الجليدي الذكي (Ice Cooling Fabric)',
    nameEn: 'Phase Change Cooling Ice-Silk Fabric (400g/m²)',
    category: 'fabric',
    code: 'TX-COL-400',
    standardThicknessMinCm: 0.5,
    standardThicknessMaxCm: 2.0,
    standardThicknessDefaultCm: 1.0,
    densityRangeKgM3: [350, 450],
    defaultDensityKgM3: 400,
    costPerM2Sar: 38,
    supplierName: 'مجمع نسيج سليبي المعتمد (Sleepee Master Textile)',
    supplierCode: 'SUP-TEX-CL02',
    firmnessFactor: 4.0,
    durabilityYears: 10,
    thermalConductivity: 'high',
    sasoCompliant: true,
    medicalGrade: false,
    hotelGrade: true,
    notesAr: 'قماش حريري جليدي بألياف ناقلة للحرارة تبدد الدفء فور ملامسة الجسم وتمنح إحساساً فورياً بالانتعاش.',
    notesEn: 'Conductive cooling yarn fabric dissipating body heat instantly for uninterrupted restorative sleep.'
  },
  'Organic Fabric': {
    id: 'mat-fab-org',
    nameAr: 'قماش عضوي معالج مضاد للبكتيريا (Organic Anti-Bacterial Fabric)',
    nameEn: 'Sanitized 100% Organic Cotton Fabric (320g/m²)',
    category: 'fabric',
    code: 'TX-ORG-320',
    standardThicknessMinCm: 0.5,
    standardThicknessMaxCm: 2.0,
    standardThicknessDefaultCm: 1.0,
    densityRangeKgM3: [300, 380],
    defaultDensityKgM3: 320,
    costPerM2Sar: 30,
    supplierName: 'مجمع نسيج سليبي المعتمد (Sleepee Master Textile)',
    supplierCode: 'SUP-TEX-OR03',
    firmnessFactor: 4.5,
    durabilityYears: 10,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'قماش قطني عضوي معتمد بمعالجة Sanitized الطبية لمكافحة البكتيريا، الفطريات، وحساسية الجلد.',
    notesEn: 'GOTS certified organic cotton fabric treated with anti-microbial Silver-Ion sanitation.'
  },
  'Tencel': {
    id: 'mat-fab-tencel',
    nameAr: 'قماش التنسيل الطبيعي الفاخر (Natural Tencel Fabric)',
    nameEn: 'Eco-Friendly Tencel Eucalyptus Fibers (360g/m²)',
    category: 'fabric',
    code: 'TX-TNC-360',
    standardThicknessMinCm: 0.5,
    standardThicknessMaxCm: 2.0,
    standardThicknessDefaultCm: 1.0,
    densityRangeKgM3: [320, 420],
    defaultDensityKgM3: 360,
    costPerM2Sar: 32,
    supplierName: 'مجمع نسيج سليبي المعتمد (Sleepee Master Textile)',
    supplierCode: 'SUP-TEX-TN04',
    firmnessFactor: 4.0,
    durabilityYears: 10,
    thermalConductivity: 'high',
    sasoCompliant: true,
    medicalGrade: true,
    hotelGrade: true,
    notesAr: 'ألياف خشب الأوكالبتوس الطبيعية ذات الامتصاص الفائق للرطوبة ونعومة الحرير والتهوية الصحية التامة.',
    notesEn: 'Naturally derived eucalyptus lyocell fiber with high moisture absorption and silky smooth texture.'
  },
  'Jacquard': {
    id: 'mat-fab-jacq',
    nameAr: 'قماش داماسك جاكار متين (Damask Jacquard)',
    nameEn: 'Heavy Duty Woven Damask Jacquard (250g/m²)',
    category: 'fabric',
    code: 'TX-JCQ-250',
    standardThicknessMinCm: 0.5,
    standardThicknessMaxCm: 1.5,
    standardThicknessDefaultCm: 0.8,
    densityRangeKgM3: [220, 280],
    defaultDensityKgM3: 250,
    costPerM2Sar: 16,
    supplierName: 'المورد الوطني للأقمشة المنسوجة (National Woven Fabrics)',
    supplierCode: 'SUP-NAT-TX05',
    firmnessFactor: 6.0,
    durabilityYears: 8,
    thermalConductivity: 'neutral',
    sasoCompliant: true,
    medicalGrade: false,
    hotelGrade: false,
    notesAr: 'قماش جاكار متين عالي التحمل ومقاوم للتآكل والاحتكاك للمشاريع الاقتصادية والسكنية اليومية.',
    notesEn: 'Tightly woven classic damask jacquard offering friction resistance and economic durability.'
  }
};

/**
 * Industrial Standards Matrix for Sleepee Product Lines
 */
export const SLEEPEE_STANDARDS_MATRIX: MattressStandardMatrix[] = [
  {
    marketSegment: 'Hotel',
    budgetLevel: 'Luxury',
    recommendedSpring: 'Pocket Spring',
    recommendedCoreFoam: 'HR Foam',
    recommendedTopper: 'Latex',
    recommendedFabric: 'Cooling Fabric',
    minTargetHeightCm: 28,
    maxTargetHeightCm: 40,
    defaultHeightCm: 32,
    minFoamDensity: 35,
    standardWarrantyYears: 10,
    defaultWarrantyType: 'Hybrid',
    riskProfile: 'Low',
    engineeringJustificationAr: 'المعايير الفندقية الفاخرة تتطلب شاسيه سوست جيبية لعزل الحركة بنسبة 100%، مدعماً بطبقات لاتكس وإسفنج HR بكثافة 35+ كجم/م³ لتحمل الاستخدام اليومي المكثف مع ضمان هجين يقلل تكلفة الفاقد التشغيلي.',
    engineeringJustificationEn: 'Luxury hotel specifications mandate pocket coils for zero motion transfer, supported by Latex and 35+ kg/m³ HR foam to withstand heavy hospitality duty with a low warranty risk profile.'
  },
  {
    marketSegment: 'Hotel',
    budgetLevel: 'Standard',
    recommendedSpring: 'Pocket Spring',
    recommendedCoreFoam: 'HR Foam',
    recommendedTopper: 'Memory Foam',
    recommendedFabric: 'Knitted Fabric',
    minTargetHeightCm: 25,
    maxTargetHeightCm: 32,
    defaultHeightCm: 28,
    minFoamDensity: 30,
    standardWarrantyYears: 7,
    defaultWarrantyType: '7 Years',
    riskProfile: 'Low',
    engineeringJustificationAr: 'معيار الفنادق القياسي يوازن بين كلفة الإنتاج العادلة والمتانة الفائقة باستخدام سوست جيبية وإسفنج ميموري فوم مع أقمشة محاكة ضد التمزق.',
    engineeringJustificationEn: 'Standard hospitality engineering balancing production cost and commercial longevity using pocket springs and high resilience foams.'
  },
  {
    marketSegment: 'Medical',
    budgetLevel: 'Premium',
    recommendedSpring: 'No Springs',
    recommendedCoreFoam: 'Rebonded Foam',
    recommendedTopper: 'Latex',
    recommendedFabric: 'Organic Fabric',
    minTargetHeightCm: 20,
    maxTargetHeightCm: 30,
    defaultHeightCm: 25,
    minFoamDensity: 40,
    standardWarrantyYears: 10,
    defaultWarrantyType: '10 Years',
    riskProfile: 'Low',
    engineeringJustificationAr: 'المراتب الطبية المعتمدة تُبنى بقلب إسفنج ريبوند طبي عالي الكثافة (D80) لتثبيت فقرات الظهر ومنع التقوس، مغلفة بطبقة لاتكس طبيعي معقم وأقمشة قطنية عضوية خالية من مسببات الحساسية.',
    engineeringJustificationEn: 'Certified orthopedic medical grade build with D80 rebonded foam spinal stabilizer core, natural latex cushioning, and hypoallergenic organic sanitization.'
  },
  {
    marketSegment: 'Medical',
    budgetLevel: 'Standard',
    recommendedSpring: 'Micro Pocket',
    recommendedCoreFoam: 'HR Foam',
    recommendedTopper: 'Gel Memory Foam',
    recommendedFabric: 'Organic Fabric',
    minTargetHeightCm: 22,
    maxTargetHeightCm: 30,
    defaultHeightCm: 26,
    minFoamDensity: 35,
    standardWarrantyYears: 10,
    defaultWarrantyType: '10 Years',
    riskProfile: 'Low',
    engineeringJustificationAr: 'هندسة طبية هجينة تعتمد على سوست Micro Pocket الدقيقة لتخفيف الضغط الارتدادي عن المفاصل مع جل ميموري فوم لتبريد السطح ومنع التقرحات السريرية.',
    engineeringJustificationEn: 'Hybrid medical engineering with micro pocket pressure-relief coils and cooling gel memory foam for clinical decubitus prevention.'
  },
  {
    marketSegment: 'Retail',
    budgetLevel: 'Premium',
    recommendedSpring: 'Pocket Spring',
    recommendedCoreFoam: 'HR Foam',
    recommendedTopper: 'Memory Foam',
    recommendedFabric: 'Tencel',
    minTargetHeightCm: 26,
    maxTargetHeightCm: 35,
    defaultHeightCm: 30,
    minFoamDensity: 32,
    standardWarrantyYears: 10,
    defaultWarrantyType: '10 Years',
    riskProfile: 'Low',
    engineeringJustificationAr: 'تصميم تجزئة فاخر يوفر توازناً مثالياً بين النعومة والدعم العميق، مع قماش التنسيل الصديق للبيئة و10 سنوات ضمان معتمد.',
    engineeringJustificationEn: 'Premium retail consumer configuration pairing contouring memory foam with responsive pocket coils encased in breathable tencel fabric.'
  },
  {
    marketSegment: 'Retail',
    budgetLevel: 'Economy',
    recommendedSpring: 'Bonnell Spring',
    recommendedCoreFoam: 'Hard Foam',
    recommendedTopper: 'Soft Foam',
    recommendedFabric: 'Jacquard',
    minTargetHeightCm: 18,
    maxTargetHeightCm: 24,
    defaultHeightCm: 22,
    minFoamDensity: 24,
    standardWarrantyYears: 5,
    defaultWarrantyType: '5 Years',
    riskProfile: 'Medium',
    engineeringJustificationAr: 'هيكل اقتصادي متين يعتمد على شاسيه سوست بونيل كربوني مدعم بلباد قطني عازل وإسفنج دعم صلب، يحقق أعلى كفاءة سعرية مع ضمان 5 سنوات.',
    engineeringJustificationEn: 'Economical robust structure utilizing heavy-duty Bonnell spring frame protected by thermo-felt and base foam with a 5-year warranty.'
  },
  {
    marketSegment: 'Export',
    budgetLevel: 'Standard',
    recommendedSpring: 'Pocket Spring',
    recommendedCoreFoam: 'HR Foam',
    recommendedTopper: 'Memory Foam',
    recommendedFabric: 'Knitted Fabric',
    minTargetHeightCm: 20,
    maxTargetHeightCm: 28,
    defaultHeightCm: 25,
    minFoamDensity: 32,
    standardWarrantyYears: 7,
    defaultWarrantyType: '7 Years',
    riskProfile: 'Low',
    engineeringJustificationAr: 'هيكل مخصص للتصدير والشحن المضغوط (Roll-Pack Vacuum) باستخدام خامات عالية الارتداد تستعيد 100% من أبعادها خلال ساعتين من الفتح.',
    engineeringJustificationEn: 'Export roll-pack vacuum compression certified architecture engineered with high-resilience memory polymers restoring 100% volume post unboxing.'
  }
];
